/**
 * A LiveKit stand-in for Expo Go, where there is no WebRTC native module.
 *
 * This exists so the screen can be developed on a real phone by scanning a QR
 * code, with no build step. It renders the same component tree against fake
 * state. It is NOT a capture path and proves nothing about audio.
 *
 * The one rule this file must not break, from ../CLAUDE.md: silence is the
 * expected failure mode on mobile and it looks exactly like success. A moving
 * meter here is generated by Math.sin, so a moving meter in Expo Go must never
 * be read as evidence that audio is flowing. That is why ./livekit exports
 * IS_PREVIEW and why App.tsx puts a banner on screen whenever it is true —
 * the mock is only safe if it is impossible to mistake for the real thing.
 *
 * Shapes here mirror only the slice of the API that App.tsx actually touches.
 */
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";

// String values match livekit-client's real enums, because App.tsx renders the
// connection state directly as text.
export const ConnectionState = {
  Disconnected: "disconnected",
  Connecting: "connecting",
  Connected: "connected",
  Reconnecting: "reconnecting",
  SignalReconnecting: "signalReconnecting",
} as const;

export const Track = {
  Source: {
    Camera: "camera",
    Microphone: "microphone",
    ScreenShare: "screen_share",
    ScreenShareAudio: "screen_share_audio",
    Unknown: "unknown",
  },
} as const;

// No native audio session to start. Resolving keeps App.tsx's mount effect on
// its happy path instead of showing an error that is not real.
export const AudioSession = {
  startAudioSession: async () => {},
  stopAudioSession: async () => {},
  configureAudio: async () => {},
};

// In a dev build this installs WebRTC onto globalThis. There is nothing to
// install without the native module, so it is a deliberate no-op.
export const registerGlobals = () => {};

type PreviewRoom = {
  connection: string;
  micEnabled: boolean;
  setMicEnabled: (on: boolean) => void;
};

const RoomContext = createContext<PreviewRoom | null>(null);

function useRoom(): PreviewRoom {
  const room = useContext(RoomContext);
  if (!room) {
    throw new Error("Preview LiveKit hooks must be used inside <LiveKitRoom>.");
  }
  return room;
}

export function LiveKitRoom({
  children,
  connect = true,
}: {
  children?: ReactNode;
  serverUrl?: string;
  token?: string;
  audio?: boolean;
  video?: boolean;
  connect?: boolean;
  onDisconnected?: () => void;
  onError?: (error: Error) => void;
}) {
  const [connection, setConnection] = useState<string>(ConnectionState.Connecting);
  const [micEnabled, setMicEnabled] = useState(true);

  // A short delay so the connecting spinner and the status dot are both
  // exercised, rather than snapping straight to connected.
  useEffect(() => {
    if (!connect) {
      setConnection(ConnectionState.Disconnected);
      return;
    }
    setConnection(ConnectionState.Connecting);
    const timer = setTimeout(() => setConnection(ConnectionState.Connected), 900);
    return () => clearTimeout(timer);
  }, [connect]);

  const value = useMemo<PreviewRoom>(
    () => ({ connection, micEnabled, setMicEnabled }),
    [connection, micEnabled],
  );

  return <RoomContext.Provider value={value}>{children}</RoomContext.Provider>;
}

export function useConnectionState() {
  return useRoom().connection;
}

export function useLocalParticipant() {
  const room = useRoom();
  const setMicrophoneEnabled = useCallback(
    async (on: boolean) => room.setMicEnabled(on),
    [room],
  );

  const localParticipant = useMemo(
    () => ({
      identity: "you",
      isLocal: true,
      isMicrophoneEnabled: room.micEnabled,
      setMicrophoneEnabled,
    }),
    [room.micEnabled, setMicrophoneEnabled],
  );

  return { localParticipant };
}

// Two fixed participants: you, plus one stand-in for the second party. Frozen
// in a module constant so the identities stay referentially stable and React
// keys never churn between renders.
const PREVIEW_TRACKS = [
  {
    participant: { identity: "you", isLocal: true },
    publication: { trackSid: "preview-local" },
    source: Track.Source.Microphone,
  },
  {
    participant: { identity: "guest-laptop", isLocal: false },
    publication: { trackSid: "preview-remote" },
    source: Track.Source.Microphone,
  },
];

export function useTracks(_sources?: unknown) {
  const { connection } = useRoom();
  // Nothing is published until the room reports connected, which is what the
  // real hook does and what App.tsx's empty state is written against.
  return connection === ConnectionState.Connected ? PREVIEW_TRACKS : [];
}

export function useTrackVolume(trackRef?: {
  participant?: { isLocal?: boolean; identity?: string };
}) {
  const { micEnabled } = useRoom();
  const isLocal = Boolean(trackRef?.participant?.isLocal);
  const muted = isLocal && !micEnabled;

  const [volume, setVolume] = useState(0);
  // Offset per participant so the two bars do not move in lockstep, which
  // would read as one signal duplicated rather than two speakers.
  const phase = useRef(isLocal ? 0 : Math.PI / 2);

  useEffect(() => {
    if (muted) {
      setVolume(0);
      return;
    }
    const timer = setInterval(() => {
      phase.current += 0.35;
      const swell = (Math.sin(phase.current) + 1) / 2;
      setVolume(Math.min(1, swell * 0.65 + Math.random() * 0.2));
    }, 120);
    return () => clearInterval(timer);
  }, [muted]);

  return volume;
}
